-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfNi3+TAczAIhzINP
2yrftcGGqfkAeoaGQDqYIC9G+G6gCgYIKoZIzj0DAQehRANCAARUnIfUVzN7UpGX
DvBPuPe+YWLWjVUNxGWyXKEIxdBjpP5qeWWQ0CK3LOUpTI1WfO9zE8N4xCorQ2Lz
geumBzAa
-----END PRIVATE KEY-----